In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Chinnu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Chinnu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
resumes = pd.read_csv("../data/UpdatedResumeDataSet.csv")
jobs = pd.read_csv("../data/job_roles.csv")

In [5]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [11]:
def clean_text(text):
    text = str(text).lower()
    
    # replace separators with space
    text = re.sub(r'[\|,/]', ' ', text)
    
    # remove urls
    text = re.sub(r'http\S+', '', text)
    
    # remove special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    words = text.split()
    
    # remove stopwords + lemmatization
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    
    return " ".join(words)

In [12]:
resumes['cleaned_resume'] = resumes['Resume'].apply(clean_text)

In [13]:
jobs['cleaned_skills'] = jobs['Required Skills'].apply(clean_text)

In [14]:
resumes[['Resume','cleaned_resume']].head()

,Resume,cleaned_resume
0,Skills * Programming Languages: Python (pandas...,skill programming language python panda numpy ...
1,Education Details \r\nMay 2013 to May 2017 B.E...,education detail may may uitrgpv data scientis...
2,"Areas of Interest Deep Learning, Control Syste...",area interest deep learning control system des...
3,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skill r python sap hana tableau sap hana sql s...
4,"Education Details \r\n MCA YMCAUST, Faridab...",education detail mca ymcaust faridabad haryana...

In [15]:
jobs[['Required Skills','cleaned_skills']].head()

,Required Skills,cleaned_skills
0,Python|Java|C++|Git|Software Design|Problem So...,python java c git software design problem solving
1,JavaScript|React|Node.js|HTML/CSS|Database|Git,javascript react nodejs html cs database git
2,JavaScript|React|Vue.js|CSS|HTML|UI/UX Design,javascript react vuejs cs html ui ux design
3,Python|Java|Node.js|Database Design|API Develo...,python java nodejs database design api develop...
4,Docker|Kubernetes|AWS|Linux|CI/CD|Scripting,docker kubernetes aws linux ci cd scripting

In [16]:
resumes.to_csv("../data/resumes_cleaned.csv", index=False)
jobs.to_csv("../data/jobs_cleaned.csv", index=False)